tenancy_ocid        = "seu_ocid-aqui"
user_ocid           = "seu_user_ocid_aqui"
region              = "regiao_aqui"
compartment_ocid    = "seu_compartment_ocid_aqui"
windows_image_ocid  = "windows_image_ocid_aqui"
